export const LOGIN_API_CALL_REQUEST = "LOGIN_API_CALL_REQUEST";
export const LOGIN_API_CALL_SUCCESS = "LOGIN_API_CALL_SUCCESS";
export const LOGIN_API_CALL_FAILURE = "LOGIN_API_CALL_FAILURE";
export const CHANGE_SELECTED_PROFILE = "CHANGE_SELECTED_PROFILE";